// https://typeofnan.dev/setup-a-typescript-react-redux-project/
export function typedAction<T extends string>(type: T): { type: T };
export function typedAction<T extends string, P>(type: T, payload: P): { type: T; payload: P };
export function typedAction(type: string, payload?: any) {
  return { type, payload };
}

// Common
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_START = "API_CALL_START";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const LIST_COUNTRIES_LOADING = "LIST_COUNTRIES_LOADING";
export const LIST_COUNTRIES_ERROR = "LIST_COUNTRIES_ERROR";
export const LIST_COUNTRIES_COMPLETE = "LIST_COUNTRIES_COMPLETE";

export const LIST_BUSINESS_UNITS_LOADING = "LIST_BUSINESS_UNITS_LOADING";
export const LIST_BUSINESS_UNITS_ERROR = "LIST_BUSINESS_UNITS_ERROR";
export const LIST_BUSINESS_UNITS_COMPLETE = "LIST_BUSINESS_UNITS_COMPLETE";

export const LIST_CHARTS_LOADING = "LIST_CHARTS_LOADING";
export const LIST_CHARTS_ERROR = "LIST_CHARTS_ERROR";
export const LIST_CHARTS_COMPLETE = "LIST_CHARTS_COMPLETE";

// world-overview
export const FETCH_ACTIVE_MEMBERS_REPORT_LOADING = "FETCH_ACTIVE_MEMBERS_REPORT_LOADING";
export const FETCH_ACTIVE_MEMBERS_REPORT_ERROR = "FETCH_ACTIVE_MEMBERS_REPORT_ERROR";
export const FETCH_ACTIVE_MEMBERS_REPORT_COMPLETE = "FETCH_ACTIVE_MEMBERS_REPORT_COMPLETE";

export const FETCH_NEW_MEMBERS_REPORT_LOADING = "FETCH_NEW_MEMBERS_REPORT_LOADING";
export const FETCH_NEW_MEMBERS_REPORT_ERROR = "FETCH_NEW_MEMBERS_REPORT_ERROR";
export const FETCH_NEW_MEMBERS_REPORT_COMPLETE = "FETCH_NEW_MEMBERS_REPORT_COMPLETE";

export const FETCH_AUTO_OFFBOARDED_MEMBERS_REPORT_LOADING =
  "FETCH_AUTO_OFFBOARDED_MEMBERS_REPORT_LOADING";
export const FETCH_AUTO_OFFBOARDED_MEMBERS_REPORT_ERROR =
  "FETCH_AUTO_OFFBOARDED_MEMBERS_REPORT_ERROR";
export const FETCH_AUTO_OFFBOARDED_MEMBERS_REPORT_COMPLETE =
  "FETCH_AUTO_OFFBOARDED_MEMBERS_REPORT_COMPLETE";

export const FETCH_SELF_RESIGNED_MEMBERS_REPORT_LOADING =
  "FETCH_SELF_RESIGNED_MEMBERS_REPORT_LOADING";
export const FETCH_SELF_RESIGNED_MEMBERS_REPORT_ERROR = "FETCH_SELF_RESIGNED_MEMBERS_REPORT_ERROR";
export const FETCH_SELF_RESIGNED_MEMBERS_REPORT_COMPLETE =
  "FETCH_SELF_RESIGNED_MEMBERS_REPORT_COMPLETE";

// Employees
export const SEARCH_EMPLOYEE_LOADING = "SEARCH_EMPLOYEE_LOADING";
export const SEARCH_EMPLOYEE_ERROR = "SEARCH_EMPLOYEE_ERROR";
export const SEARCH_EMPLOYEE_COMPLETE = "SEARCH_EMPLOYEE_COMPLETE";

export const SEARCH_EMPLOYEES_LOADING = "SEARCH_EMPLOYEES_LOADING";
export const SEARCH_EMPLOYEES_ERROR = "SEARCH_EMPLOYEES_ERROR";
export const SEARCH_EMPLOYEES_COMPLETE = "SEARCH_EMPLOYEES_COMPLETE";

export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";
export const UPDATE_EMPLOYEE_COMPLETE = "UPDATE_EMPLOYEE_COMPLETE";

export const DELETE_EMPLOYEE_LOADING = "DELETE_EMPLOYEE_LOADING";
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR";
export const DELETE_EMPLOYEE_COMPLETE = "DELETE_EMPLOYEE_COMPLETE";

// Documents
export const SEARCH_DOCUMENT_LOADING = "SEARCH_DOCUMENT_LOADING";
export const SEARCH_DOCUMENT_ERROR = "SEARCH_DOCUMENT_ERROR";
export const SEARCH_DOCUMENT_COMPLETE = "SEARCH_DOCUMENT_COMPLETE";

export const SEARCH_DOCUMENTS_LOADING = "SEARCH_DOCUMENTS_LOADING";
export const SEARCH_DOCUMENTS_ERROR = "SEARCH_DOCUMENTS_ERROR";
export const SEARCH_DOCUMENTS_COMPLETE = "SEARCH_DOCUMENTS_COMPLETE";

export const CREATE_DOCUMENT_LOADING = "CREATE_DOCUMENT_LOADING";
export const CREATE_DOCUMENT_ERROR = "CREATE_DOCUMENT_ERROR";
export const CREATE_DOCUMENT_COMPLETE = "CREATE_DOCUMENT_COMPLETE";

export const UPDATE_DOCUMENT_LOADING = "UPDATE_DOCUMENT_LOADING";
export const UPDATE_DOCUMENT_ERROR = "UPDATE_DOCUMENT_ERROR";
export const UPDATE_DOCUMENT_COMPLETE = "UPDATE_DOCUMENT_COMPLETE";

export const DELETE_DOCUMENT_LOADING = "DELETE_DOCUMENT_LOADING";
export const DELETE_DOCUMENT_ERROR = "DELETE_DOCUMENT_ERROR";
export const DELETE_DOCUMENT_COMPLETE = "DELETE_DOCUMENT_COMPLETE";

// Groups
export const SEARCH_GROUP_LOADING = "SEARCH_GROUP_LOADING";
export const SEARCH_GROUP_ERROR = "SEARCH_GROUP_ERROR";
export const SEARCH_GROUP_COMPLETE = "SEARCH_GROUP_COMPLETE";

export const SEARCH_GROUPS_LOADING = "SEARCH_GROUPS_LOADING";
export const SEARCH_GROUPS_ERROR = "SEARCH_GROUPS_ERROR";
export const SEARCH_GROUPS_COMPLETE = "SEARCH_GROUPS_COMPLETE";

export const CREATE_GROUP_LOADING = "CREATE_GROUP_LOADING";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";
export const CREATE_GROUP_COMPLETE = "CREATE_GROUP_COMPLETE";

export const UPDATE_GROUP_LOADING = "UPDATE_GROUP_LOADING";
export const UPDATE_GROUP_ERROR = "UPDATE_GROUP_ERROR";
export const UPDATE_GROUP_COMPLETE = "UPDATE_GROUP_COMPLETE";

export const DELETE_GROUP_LOADING = "DELETE_GROUP_LOADING";
export const DELETE_GROUP_ERROR = "DELETE_GROUP_ERROR";
export const DELETE_GROUP_COMPLETE = "DELETE_GROUP_COMPLETE";

export const DEACTIVATE_GROUP_LOADING = "DEACTIVATE_GROUP";
export const DEACTIVATE_GROUP_ERROR = "DEACTIVATE_GROUP_ERROR";
export const DEACTIVATE_GROUP_COMPLETE = "DEACTIVATE_GROUP_COMPLETE";

export const ADD_EMPLOYEE_TO_GROUP_LOADING = "ADD_EMPLOYEE_TO_GROUP_LOADING";
export const ADD_EMPLOYEE_TO_GROUP_ERROR = "ADD_EMPLOYEE_TO_GROUP_ERROR";
export const ADD_EMPLOYEE_TO_GROUP_COMPLETE = "ADD_EMPLOYEE_TO_GROUP_COMPLETE";

export const REMOVE_EMPLOYEE_FROM_GROUP_LOADING = "REMOVE_EMPLOYEE_FROM_GROUP_LOADING";
export const REMOVE_EMPLOYEE_FROM_GROUP_ERROR = "REMOVE_EMPLOYEE_FROM_GROUP_ERROR";
export const REMOVE_EMPLOYEE_FROM_GROUP_COMPLETE = "REMOVE_EMPLOYEE_FROM_GROUP_COMPLETE";
